import type { Project } from "./types"

export const projects: Project[] = [
  {
    id: 1,
    title: "DealHarbor",
    slug: "deal-harbor",
    shortDescription: "E-commerce platform with real-time deals and personalized recommendations",
    description:
      "DealHarbor is a comprehensive e-commerce platform that focuses on providing users with real-time deals and personalized product recommendations. The platform integrates with multiple payment gateways and features an advanced search system with filters.",
    features: [
      "Real-time deal tracking and notifications",
      "Personalized product recommendations using ML algorithms",
      "Advanced search with multiple filtering options",
      "Secure checkout with multiple payment options",
      "Responsive design for all devices",
    ],
    challenges:
      "One of the main challenges was implementing the real-time deal tracking system that could handle thousands of concurrent users without performance degradation. I solved this by implementing a WebSocket-based architecture with Redis for caching and pub/sub messaging.",
    timeline: "4 months (Jan 2023 - Apr 2023)",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Node.js", "MongoDB", "Redis", "WebSockets"],
    githubUrl: "https://github.com/NitinTheGreat/deal-harbor",
    liveUrl: "https://dealharbor.me",
    images: [
      "/dealharbor/1.jpeg",
      "/dealharbor/2.jpeg",
      " /dealharbor/3.jpeg",
      "/dealharbor/4.jpeg",
      "/dealharbor/5.jpeg",
      "/dealharbor/6.jpeg",
      "/dealharbor/7.jpeg",
      "/dealharbor/8.jpeg",
      "/dealharbor/9.jpeg",
      "/dealharbor/10.jpeg",
      "/dealharbor/11.jpeg",
      "/dealharbor/12.jpeg",
      "/dealharbor/13.jpeg",
    ],
    isHighlighted: true,
  },
  {
    id: 2,
    title: "Riviera'25 Website",
    slug: "riviera-25",
    shortDescription: "Official website for Riviera'25, a cultural and technical festival",
    description:
      "Designed and developed the official website for Riviera'25 with complete SSR and enhanced SEO. The website features event registration, schedule management, and real-time updates for attendees.",
    features: [
      "Online event registration and ticket booking",
      "Interactive schedule with filtering options",
      "Real-time updates and announcements",
      "User authentication and profile management",
      "Admin dashboard for event management",
    ],
    challenges:
      "The main challenge was handling peak traffic during the event registration period. I implemented a queue-based registration system with Cloudflare caching to ensure the website remained responsive even during high traffic periods.",
    timeline: "3 months (Sep 2022 - Nov 2022)",
    technologies: ["React", "Next.js", "Firebase", "Framer Motion", "Tailwind CSS", "Cloudflare"],
    githubUrl: "https://github.com/NitinTheGreat/riviera25-old",
    liveUrl: "https://riviera.vit.ac.in",
    images: [
      "/riviera/1.png",
      "/riviera/2.png",
      "/riviera/3.png",
      "/riviera/4.png",
      "/riviera/5.png",
      "/riviera/6.png",
      "/riviera/7.png",
      "/riviera/8.png",
      "/riviera/9.png",
      "/riviera/10.png",
      "/riviera/11.png",
    ],
    isHighlighted: true,
  },
  {
    id: 3,
    title: "StreetGuardian",
    slug: "street-guardian",
    shortDescription: "AI-powered road safety monitoring system with real-time alerts",
    description:
      "StreetGuardian is an AI-powered road safety monitoring system that uses computer vision to detect traffic violations, accidents, and hazardous conditions in real-time. The system sends alerts to relevant authorities and provides a dashboard for monitoring.",
    features: [
      "Real-time video analysis using computer vision",
      "Automatic detection of traffic violations and accidents",
      "Alert system for emergency services",
      "Historical data analysis and reporting",
      "Mobile app for on-the-go monitoring",
    ],
    challenges:
      "The biggest challenge was optimizing the computer vision algorithms to run efficiently on edge devices with limited computing power. I implemented model quantization and used TensorFlow Lite to ensure the system could run on various hardware configurations.",
    timeline: "6 months (May 2022 - Oct 2022)",
    technologies: ["Python", "TensorFlow", "OpenCV", "React", "Node.js", "MongoDB", "WebRTC"],
    githubUrl: "https://github.com/NItinTheGreat/street-guardian",
    liveUrl: "https://streetguardian.tech",
    images: [
      "/streetguardian/1.jpeg",
      "/streetguardian/2.jpeg",
      "/streetguardian/3.jpeg", 
      "/streetguardian/4.jpeg",
      "/streetguardian/5.jpeg",
      "/streetguardian/6.jpeg",
      "/streetguardian/7.jpeg",
    ],
    isHighlighted: true,
  },
  {
    id: 4,
    title: "AO3 Chrome Extension",
    shortDescription: "Real-time collaborative code editor with video chat",
    description:
      "This browser extension enhances your AO3 reading experience by offering smart recommendations and personalized note-taking all in one seamless tool.  Personalized Recommendations: Get new fanfiction suggestions based on your reading history, Story Notes: Save and revisit your thoughts for any fic.  ",
    technologies: ["React", "Node.js", "Express.js", "MongoDB", "Python", "TensorFlow", ""],
    githubUrl: "https://github.com/NitinTheGreat/codecollab",
    liveUrl: "https://codecollab.example.com",
    images: ["/ao3/1.jpeg", "/ao3/2.jpeg"],
  },
  {
    id: 5,
    title: "WomenTechies'25 Website",
    shortDescription: "Web app to upscale and enhance low-resolution images using AI.",
    description:
      "An AI-powered image upscaling tool that uses deep learning to increase the resolution of images while preserving detail and quality.",
    technologies: ["React.js", "Framer Motion", "Tailwind CSS"],
    githubUrl: "https://github.com/NitinTheGreat/WomenTechies25.git",
    liveUrl:"https://women-techies25.vercel.app/",
    images: ["/WT/1.png", "/WT/2.png", "/WT/3.png", "/WT/4.png", "/WT/5.png", "/WT/6.png"],
  },
  {
    id: 6,
    title: "Python Railway Reservation Project",
    shortDescription: "My first Python project, a railway reservation system as part of my class 12th project.",
    description:
      "A simple railway reservation system built using Python, MySQL and Tkinter. It allows users to book, cancel, and view train tickets.",
    technologies: ["Python", "Tkinter","MySQL"],
    githubUrl: "https://github.com/NitinTheGreat/Python-Railway-Reservation-Project.git",
    liveUrl: "https://github.com/NitinTheGreat/Python-Railway-Reservation-Project.git",
    images: ["/railway/1.jpeg", "/railway/2.jpeg", "/railway/3.jpeg", "/railway/4.jpeg", "/railway/5.jpeg", "/railway/6.jpeg"],
  },
]

export const highlightedProjects = projects.filter((p) => p.isHighlighted)
